Use credentials from bundler config
manveru/bundix pull request #40
Opened 2019-01-16 23:03 UTC by burke

login:password [can be specified in bundler configs](https://bundler.io/v1.15/man/bundle-config.1.html#CREDENTIALS-FOR-GEM-SOURCES
).

This behaviour feels a little more in line with how bundler itself operates.

2019-01-16 23:10 UTC, burke commented on lib/bundix/source.rb
> +          .scan(/^(?<key>BUNDLE_.*?):\s*(?<username>.*)(?::(?<password>.*))?/)
I wasn't sure whether this project wanted to rely on YAML being available so I didn't do this "correctly", but happy to revise to actually parse the file if that would be preferable.

2019-01-17 11:52 UTC, alyssais requested changes
I'd prefer that we `require "bundler"` and use it to pull the data we need to fetch. Reimplementing this ourselves is brittle and won't capture the intricacies of how Bundler works. For example, Bundler allows the config file location to be customised, but with this patch authentication would fail in that case.

2019-01-17 17:56 UTC, burke commented
Ok great, that's probably a simpler implementation anyway. I'll revise this today. :+1:

2019-01-17 19:33 UTC, burke commented
I've revised this PR to use `Bundler::Settings` directly, and to gracefully handle the case where bundler isn't available, for whatever reason.

With an incorrect token, then a correct one:

![screen shot 2019-01-17 at 2 31 22 pm](https://user-images.githubusercontent.com/1284/51343525-9deb3500-1a64-11e9-945b-1914e1673649.png)

2019-01-17 19:37 UTC, burke commented
Though, I'm confused by this:

```
building '/nix/store/v408l83vns1548cwnvqa0m11xfr65zl1-gemfile-and-lockfile.drv'...
building '/nix/store/a22rs6cn6pyiql2rciygfmhrzs71vm8g-shopify-cops-0.0.11.gem.drv'...

trying https://packages.shopify.io/shopify/gems/gems/shopify-cops-0.0.11.gem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized
error: cannot download shopify-cops-0.0.11.gem from any mirror
builder for '/nix/store/a22rs6cn6pyiql2rciygfmhrzs71vm8g-shopify-cops-0.0.11.gem.drv' failed with exit code 1
cannot build derivation '/nix/store/rdzhzhmd716pmk55d67ncf4rcrn7m6wv-ruby2.5.3-shopify-cops-0.0.11.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2dk6sidr07wam9v99wl83x6i6y8vmq01-dev.drv': 1 dependencies couldn't be built
error: build of '/nix/store/2dk6sidr07wam9v99wl83x6i6y8vmq01-dev.drv' failed
```

Isn't the purpose of this code that I've modified to prefetch the `*.gem` files so that `nix` won't have to do it later? Am I misunderstanding? Is there other code to teach about bundler credentials, or is it somehow mis-predicting the derivation hash?

2019-01-19 17:31 UTC, alyssais commented
Have you tried deleting gemset.nix? There’s something weird that happens when it already exists that I haven’t had the time to track down yet.

2019-01-22 22:16 UTC, burke commented
The issue was that Bundix inserts into the nix-store entries like:
"q3vq532pnpvq19sca3ccgi5yabi71y2x-https_rubygems_org_gems_rubocop-0_60_0_gem", while `bundlerEnv` seems to expect `06sp9w0i042db7y8h1gx7vwkyiw4cmpx-rubocop-0.60.0.gem`. 

This would cause the gems to be downloaded twice: once by `bundix` and then again by `bundlerEnv`. Since I haven't provided `bundlerEnv` with a way to retrieve credentials, that failed.

I've amended this PR to write files into the store at the correct paths as expected by `bundlerEnv`.

I also removed some dead code: I'm happy to move this to its own PR if it's easier to review that way but it seemed like a fairly simple thing to tack on here.

2019-03-12 20:42 UTC, burke commented
(Bump) I got pulled onto another sub-project for a while but this change still seems to fix bundix for our use-case. Let me know if there's anything I can do to help shepherd this along.

2019-03-13 12:20 UTC, zimbatm commented
it looks good to me on principle. It would be nice to have some tests but the infrastructure isn't there.

2019-03-13 17:58 UTC, burke commented
Fair, I'll try to find a way to test it later this week :+1:

2019-03-13 20:20 UTC, burke commented
I've added a test for the credential injection, happy to keep revising if necessary.

2019-03-14 17:14 UTC, merged

2019-03-14 17:14 UTC, zimbatm commented
brilliant, thanks @burke !